name: build
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    name: "build linux amd64"
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "setup go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: "prepare bin folder"
        run: "mkdir bin"
      - name: "build windows amd64"
        run: "GOOS=windows GOARCH=amd64 go build -o bin/ntgrrc-${{ steps.get_version.outputs.VERSION }}-windows-amd64.exe ntgrrc"
      - name: "build linux amd64"
        run: "GOOS=linux GOARCH=amd64 go build -o bin/ntgrrc-${{ steps.get_version.outputs.VERSION }}-linux-amd64 ntgrrc"
      - name: "build darwin amd64"
        run: "GOOS=darwin GOARCH=amd64 go build -o bin/ntgrrc-${{ steps.get_version.outputs.VERSION }}-darwin-amd64 ntgrrc"
