name: build
on: [release]
jobs:
  build-linux-amd64:
    needs: test
    runs-on: ubuntu-latest
    name: "build linux amd64"
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "setup go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: "go build ntgrrc"
        run: |
          go build ntgrrc
