name: go test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: "go test"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: "go test ntgrrc"
        run: |
          go test ntgrrc
  build-linux-amd64:
    needs: test

    runs-on: ubuntu-latest
    name: "build linux amd64"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: "go test ntgrrc"
        run: |
          go test ntgrrc
